# Generated by Django 5.0 on 2024-02-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_colorvarient_sizevarient_product_color_varient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorVarient',
            new_name='ColorVariant',
        ),
        migrations.RenameModel(
            old_name='sizeVarient',
            new_name='SizeVariant',
        ),
    ]
