# Generated by Django 5.0 on 2024-02-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_colorvarient_colorvariant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_desription',
            new_name='product_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_varient',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_varient',
        ),
        migrations.AddField(
            model_name='product',
            name='color_variants',
            field=models.ManyToManyField(blank=True, to='products.colorvariant'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_variants',
            field=models.ManyToManyField(blank=True, to='products.sizevariant'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='categories'),
        ),
    ]
